### ISSUE TITLE
What companies are using babashka and/or sci? (at least one person at a company counts!) 

### ISSUE THREAD

**Issue by borkdude** [babashka/sci#270]
Follow up at https://github.com/borkdude/babashka/issues/254

**Comment by mtruyens** [comment]
Hi, 

My legal technology startup ClauseBase (www.clausebase.com, contract drafting) uses SCI to cover the few situations where our software's own DSL cannot meet the custom logic required to draft a certain contract. 

Implementation was a breeze, many thanks!

**Comment by borkdude** [comment]
I now made a Github discussion from this:

https://github.com/babashka/sci/discussions/662

Please share your story again there!
