### ISSUE TITLE
Missing clojure.core/*clojure-version*

### ISSUE THREAD

**Issue by jeroenvandijk** [babashka/sci#382]
**version**

Tested with babashka v0.1.3 (Sci version 91b553a6cb6eb6c5a9ec752fb2c0e451922c4156)

**platform**

All, but tested on Mac Osx

**problem**

Exception about "Missing clojure.core/*clojure-version*"

**repro**

Deps
```
export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {  borkdude/edamame {:mvn/version "0.0.11-alpha.13"} }  }')

```
Script
```
#!/usr/bin/env bb

(require '[edamame.core :refer [parse-string]]))
```
Gives 
```
clojure.lang.ExceptionInfo: Could not resolve symbol: *clojure-version* [at clojure/tools/reader/impl/utils.clj, line 17, column 35]
```
**expected behavior**

No errors

** Work around **

```clojure

(require 'clojure.core)
(in-ns 'clojure.core)

(def *clojure-version* {:major      1
                        :minor      10
                       :incremental 1
                       :qualifier   nil})
                       
;; Go back to previous ns
```

**Comment by borkdude** [comment]
Additionally, we need to expose `(clojure-version)` as well. I'd say we just expose the Clojure version of the host environment, perhaps with an additional `"-sci"` modifier or so.

**Comment by borkdude** [comment]
Another note: this only applies to the JVM Clojure version, CLJS afaik doesn't have such a thing.
