### ISSUE TITLE
Is it possible to create functions at analysis time (in some cases)?

### ISSUE THREAD

**Issue by borkdude** [babashka/sci#396]
Current we call eval-fn on an analyzed object in interpreter.cljc. But in loops this means that we eval the function every time. We might get some optimization by creating the function already in analyzer.cljc. This probably means ctx it has to return a function of ctx (with `:sci.imp.op` `needs-ctx`) that we can feed to it in interpreter.cljc as the last step, but we can do all the other work in analyzer already?

**Comment by joinr** [comment]
I was just thinking something similar.  My current little test case is this:

```clojure
sci.examples.repl> (sci.impl.analyzer/analyze ctx '(dotimes [i 1000000] (+ 2 3)))
(let
 [n__14011__auto__ (#<SciVar@1b62e2c5: #function[clojure.core/long]> 1000000)]
 (let
  [i 0]
  [#:sci.impl{:fn-bodies
              [#:sci.impl{:body
                          [(if
                            (#<SciVar@5dab3c48: #function[clojure.core/<]>
                             i
                             n__14011__auto__)
                            (do
                             (#<SciVar@73bf1181: #function[clojure.core/+]>
                              2
                              3)
                             (recur
                              (#<SciVar@7f47b1f9: 
                                 #function[clojure.core/unchecked-inc]>
                               i))))],
                          :params [i],
                          :fixed-arity 1,
                          :var-arg-name nil,
                          :fn-name nil,
                          :arglist [i]}],
              :fn-name nil,
              :arglists [[i]],
              :fn true}
   i]))
```

We know all of this information at analysis time.  I am also very new at looking at the sci implementation.  My gut tells me we could probably do better.  We are currently at 1579x slower in sci jvm than clojure.  

Working on lifting vars and resolving early, via something like 

```clojure
(defn svar? [v]
  (instance? sci.impl.vars.SciVar v))

(defn find-and-replace-svars [fn-bodies]
  (let [known (atom {})
        process (fn [x]
                  (if-not (svar? x) (with-meta x (meta x))
                     (if-let [v (@known x)] v
                       (let [sym (gensym "svar")
                             _ (swap! known assoc x sym)]
                         sym))))
        new-bodies (w/prewalk process fn-bodies)]
    [new-bodies (zipmap (vals @known) (keys @known))]))


(defn lift-fn-vars [m]
  (let [fn-bodies (m :sci.impl/fn-bodies)
        [bodies bindings] (find-and-replace-svars fn-bodies)
        lifted-bindings (reduce (fn [acc [k v]] (conj acc k v)) [] bindings)]
    (with-meta `(~'let [~@lifted-bindings]
                 ~(assoc m :sci.impl/fn-bodies bodies))
      {:sci.impl/op :call})))

(defn lift-vars [frm]
  (with-meta (w/postwalk
              (fn [expr]
                (if (:sci.impl/fn-bodies expr)
                  (lift-fn-vars expr)
                  expr)) frm)
    (meta frm)))
```

It's unclear how to inline built-in function definitions if we know them at analysis time (e.g. clojure.core/+ and friends).  It would seem you have to pepper corresponding #:sci.impl{:op :resolve-sym} everywhere there's a referenced symbol.  Curious if this can be short-circuited.  There is also the option of constant folding, since we know e.g. numeric constants at analyze time can be resolved to immutable bindings.  So far, this little implementation of variable lifting isn't working, seemingly due to not invoking the proper metadata for function call and operands.  I think the tooling is there though.

**Comment by borkdude** [comment]
Note that `clojure.walk/prewalk` and `postwalk` throw away metadata. You might need a version with this patch: https://clojure.atlassian.net/browse/CLJ-2568 (consider upvoting the issue, if you find this useful).

**Comment by joinr** [comment]
Yeah, I sort of discovered that on the flip side as I was reading through the sci source trying to figure out why my lifted var analysis wasn't being interpreted.  Definitely would be useful.  Another option could be moving toward the more verbose analysis from tools.analyzer and getting away from metadata entirely, but that's a bit radical.  That would, however, provide opportunity to leverage more sophisticated passes.

**Comment by borkdude** [comment]
@joinr I should probably look more at tools.analyzer - the reason I didn't end up using it was that it didn't work with GraalVM native-image (at the time, maybe I should revisit).

**Comment by joinr** [comment]
That's a serious constraint given the intent for native-image.  I think the reader/analyzer pass should work (or could probably be made to work with minor tweaks and constraints).  It shouldn't "require" runtime class loading or eval (mostly just parsing clojure structures into maps, walking parsed ASTs of maps and emitting arbitrary code targets), although there may be some spots that leverage those things for convenience.  Ramsey Nasser (MAGIC compiler) and Tim Baldridge (old conj presentation) probably have the best walk throughs I have seen.

**Comment by borkdude** [comment]
@joinr I'm trying to understand the original intent of `lift-vars`. Why do we need to lift? The var references are already in the analyzed output which then goes into the interpreter (now called evaluator), so no additional lookups are done.

**Comment by joinr** [comment]
If you have all the references directly resolved such that the environment isn't consulted over and over again for resolution during interpretation, I think that covers what I was trying to do already.

**Comment by borkdude** [comment]
Only local binding symbols are resolved up during interpretation.
