### ISSUE TITLE
Unexpected result for non-tail usage of recur

### ISSUE THREAD

**Issue by jeroenvandijk** [babashka/sci#498]
**version**

Babashka 0.2.6 (or 5aa9031eb3692a2207106076088fcab7347c2299)

**platform**

Mac OSX

**problem**

`loop` / `recur` allows recur to be called from a non-tail position. In this particular case this gives unexpected result (doesn't recur) with an error message.

**repro**

```clojure
(loop []
    (println "hi")
    (recur)
    2)
hi
2
```

**expected behavior**

Clojure throws an error:
```
Syntax error (UnsupportedOperationException) compiling recur at (form-init7929880134577873038.clj:3:5).
Can only recur from tail position
```
Maybe the clojure behaviour would be most consistent. I'm not sure what the benefits are for not doing this (apart from having to add this check). In this particular case (adding an extra item behind `(recur)`) caught me by surprise.

**Comment by borkdude** [comment]
Note for self:

> The last expression in fn, loop, let and do forms are always in tail position; the then and else expression of an if form are also tail positions.

**Comment by borkdude** [comment]
A more efficient way to detect this is using a linter: clj-kondo/clj-kondo#1126
In this way the analyzer doesn't have to do extra work. If you aren't already using it, I recommend setting up editor integration with clj-kondo and then hopefully not too far in the future, you will get a warning about this.

**Comment by jeroenvandijk** [comment]
I agree that clj-kondo is a nice tool to catch this. Is it already possible to use clj-kondo as a (cljs) library so the linter could be used in other environments? Embedding Sci on a web page for evaluating user code would be an example use case.

**Comment by borkdude** [comment]
@jeroenvandijk Clj-kondo is currently CLJ only, but portions of it could maybe be ported to CLJS. This is a substantial amount of work though. The way I'm using it currently is as a server side service:

https://clj-kondo.michielborkent.nl/

The front-end just sends the code to the backend, the backend lints it and then returns the warnings.

**Comment by borkdude** [comment]
To be clear, clj-kondo can be used as a JVM library.

**Comment by Cnly** [comment]
I also hit this problem lately... While linters would be nice, should sci also do something about this? It should be more than a linter warning IMO.

**Comment by borkdude** [comment]
I will first address this in clj-kondo. I am also contemplating how I could address this in SCI without affecting performance too much.

**Comment by borkdude** [comment]
It's in clj-kondo now. I'll have a stab at it in SCI soon.

**Comment by borkdude** [comment]
In babashka master:

```
Type:     clojure.lang.ExceptionInfo
Message:  Can only recur from tail position
Location: /tmp/dude.clj:2:3
Phase:    analysis

----- Context ------------------------------------------------------------------
1: (defn foo []
2:   (recur)
     ^--- Can only recur from tail position
3:   1)
```

**Comment by borkdude** [comment]
Already released a while ago.
