### ISSUE TITLE
Support npm style string require

### ISSUE THREAD

**Issue by djblue** [babashka/sci#645]
**Is your feature request related to a problem? Please describe.**

When using ClojureScript, it is common to use the following syntax:

```clojure
(ns my-app (:require ["react" :as react]))
```

This denotes a javascript dependency, usually from npm.

**Describe the solution you'd like**
 
By using an explicit `get` [here](https://github.com/babashka/sci/blob/master/src/sci/impl/resolve.cljc#L56), it would allow npm dependencies to participate in the name resolution algorithm.

**Describe alternatives you've considered**

None so far.

Also, I'd be more than happy to put up a PR if you think this is a good idea.

**Comment by borkdude** [comment]
@djblue Yes, an explicit `get` would be good, PR welcome. I'm curious how you are going to use this: are you going to convert the React module to a Clojure map and put it into the namespaces config?

**Comment by borkdude** [comment]
@djblue Btw, I think it would be good to have at least one test for this to prevent future regressions.
