### ISSUE TITLE
Some array functions are missing

### ISSUE THREAD

**Issue by MrEbbinghaus** [babashka/sci#649]
**version** 0.2.7
**platform** JVM
**problem**
I noticed that some array functions like `to-array-2d` are not supported. Although `(into-array (ints [1 2])(ints [3 4))` works.

I also noticed that functions like `aget` are supported, but do not behave like the JVM clojure counterpart. 
But that would be another issue?

[I wrote some code](https://gist.github.com/MrEbbinghaus/457875dd479ab4abd2971665b291f7e1) that checks which built-in symbols sci can resolve. This is the output for array functions in the cheatsheet:

 |     :ns-name |         :name | :supported? |                                               :msg |
 | ------------ | ------------- | ----------- | -------------------------------------------------- |
 | clojure.core |        aclone |       false |      Could not resolve symbol: clojure.core/aclone |
 | clojure.core |       areduce |       false |     Could not resolve symbol: clojure.core/areduce |
 | clojure.core |   to-array-2d |       false | Could not resolve symbol: clojure.core/to-array-2d |
 | clojure.core |          amap |       false |        Could not resolve symbol: clojure.core/amap |
 | clojure.core |   short-array |        true |                                                    |
 | clojure.core |          aget |        true |                                                    |
 | clojure.core |     aset-long |        true |                                                    |
 | clojure.core |        floats |        true |                                                    |
 | clojure.core | boolean-array |        true |                                                    |
 | clojure.core |       alength |        true |                                                    |
 | clojure.core |    aset-float |        true |                                                    |
 | clojure.core |      booleans |        true |                                                    |
 | clojure.core |     int-array |        true |                                                    |
 | clojure.core |         longs |        true |                                                    |
 | clojure.core |   aset-double |        true |                                                    |
 | clojure.core |  aset-boolean |        true |                                                    |
 | clojure.core |  double-array |        true |                                                    |
 | clojure.core |     aset-char |        true |                                                    |
 | clojure.core |    aset-short |        true |                                                    |
 | clojure.core |     aset-byte |        true |                                                    |
 | clojure.core |    byte-array |        true |                                                    |
 | clojure.core |      aset-int |        true |                                                    |
 | clojure.core |    long-array |        true |                                                    |
 | clojure.core |  object-array |        true |                                                    |
 | clojure.core |       doubles |        true |                                                    |
 | clojure.core |   float-array |        true |                                                    |
 | clojure.core |          aset |        true |                                                    |
 | clojure.core |         chars |        true |                                                    |
 | clojure.core |          ints |        true |                                                    |
 | clojure.core |      to-array |        true |                                                    |
 | clojure.core |    char-array |        true |                                                    |
 | clojure.core |    make-array |        true |                                                    |
 | clojure.core |        shorts |        true |                                                    |
 | clojure.core |    into-array |        true |                                                    |

**Comment by borkdude** [comment]
Feel free to add those in `sci.impl.namespaces`. Preferably also with a test.
About `aget`, what's the problem?

**Comment by MrEbbinghaus** [comment]
Looking at the Stacktrace it could be a babashka-repl bug.

JVM Clojure
```clojure
(def array-2d (into-array [(int-array [1 2]) (int-array [3 4])]))
=> #'user/array-2d
(type array-2d)
=> [[I
(aget array-2d 0 0)
=> 1
```

Babashka:
```clojure
(def array-2d (into-array [(int-array [1 2]) (int-array [3 4])]))
=> #'user/array-2d
(type array-2d)
=> [[I
(aget array-2d 0 0)

: clojure.lang.RT user 
*e
=>
#error{:cause "clojure.lang.RT",
       :via [{:type java.lang.ClassNotFoundException,
              :message "clojure.lang.RT",
              :at [java.lang.Class forName "DynamicHub.java" 1433]}],
       :trace [[java.lang.Class forName "DynamicHub.java" 1433]
               [clojure.lang.RT classForName "RT.java" 2212]
               [clojure.lang.RT classForName "RT.java" 2221]
               [clojure.core$aget invokeStatic "core.clj" 3910]
               [clojure.core$aget doInvoke "core.clj" 3901]
               [clojure.lang.RestFn invoke "RestFn.java" 442]
               [sci.impl.analyzer$return_call$fn__8908 invoke "analyzer.cljc" 1036]
               [sci.impl.evaluator$eval invokeStatic "evaluator.cljc" 334]
               [sci.impl.interpreter$eval_form invokeStatic "interpreter.cljc" 44]
               [sci.core$eval_form invokeStatic "core.cljc" 282]
               [babashka.nrepl.impl.server$eval_msg$fn__34248$fn__34249 invoke "server.clj" 91]
               [babashka.nrepl.impl.server$eval_msg$fn__34248 invoke "server.clj" 87]
               [babashka.nrepl.impl.server$eval_msg invokeStatic "server.clj" 77]
```

**Comment by borkdude** [comment]
@MrEbbinghaus This probably has to do with reflection config in babashka. But it seems the second of `aget` which you are using here is inlined and goes through `clojure.lang.RT`:

https://github.com/clojure/clojure/blob/8ebad0ab3f912932d94874120cad89493f2aa22e/src/clj/clojure/core.clj#L3910

Note that the single arity of `aget` does work as expected:

```
$ bb -e '(def array-2d (into-array [(int-array [1 2]) (int-array [3 4])])) (-> (aget array-2d 0) (aget 0))'
1
```

Perhaps we should just patch `aget` in SCI or so, to make the second arity work better.

**Comment by borkdude** [comment]
An alternative is to add `clojure.lang.RT/aget` to the reflection config. Worth a shot.

**Comment by borkdude** [comment]
@MrEbbinghaus That does the trick:

```
./bb -e "(def array-2d (into-array [(int-array [1 2]) (int-array [3 4])])) (aget array-2d 0 0)"
1
```

You haven't specified which OS you are using with bb, but if you're using macOS:

https://24592-201467090-gh.circle-artifacts.com/0/release/babashka-0.6.9-SNAPSHOT-macos-amd64.tar.gz

**Comment by MrEbbinghaus** [comment]
Yes it does. 👍🏻

**Comment by borkdude** [comment]
@MrEbbinghaus The reported problem with `aget` have been fixed in babashka master. Are the other array functions/macros something you would like to have in SCI or is it ok to add them in bb only?

**Comment by MrEbbinghaus** [comment]
@borkdude I don't really care about these functions. 🙂 

I am using bb for [my Advent of Code solutions](https://github.com/MrEbbinghaus/advent-of-code/tree/master/2021). 
And since the task today is a large 2d grid with small numbers, ... I was interested if a byte or int array would lead to better performance than clojure vectors.
