### ISSUE TITLE
Wrong arity error messages for certain functions (apply, reduce)

### ISSUE THREAD

**Issue by Cnly** [babashka/sci#653]
**version**

This is with babashka 0.7.0 so should be https://github.com/babashka/sci/tree/573ee0e2f2ecdfc30f9f4b0d306626cacd6d3f06.

**platform**

Mac, binary

**problem**

Reducing functions lacking implementations for arities other than 2 can cause bb to give the wrong error message when used with `clojure.core/reduce`.

**repro**

```clj
(defn rf [a b] (conj a b))
(reduce rf [])
```

Result: `clojure.lang.ArityException: Wrong number of args (0) passed to: clojure.core/reduce [at <repl>:5:3]`

**expected behavior**

Correct error message given by clojure: `Wrong number of args (0) passed to: user/rf`

**Comment by rwstauner** [comment]
this is also the case for `apply`:

```
$ clj
user=> (defn foo [a b] (prn a b))
#'user/foo
user=> (apply foo [1 2 3])
Execution error (ArityException) at user/eval7940 (REPL:1).
Wrong number of args (3) passed to: user/foo
$ bb
*user=> (defn foo [a b] (prn a b))
#'user/foo
*user=> (apply foo [1 2 3] )
clojure.lang.ArityException: Wrong number of args (3) passed to: clojure.core/apply [at <repl>:2:1]
```
