### ISSUE TITLE
evaluation order of meta value

### ISSUE THREAD

**Issue by erdos** [babashka/sci#659]
**version:** Babashka 0.7.3 with sci 0.2.8
**platform:** Linux binary

**problem:**

When a map/set/vector expression has metadata map attached to it, JVM Clojure evaluates value first and metadata map second. In Babashka, the order is the opposite.

The evaluation order of expression and its meta map is inconsistent to the order in Clojure. The Clojure spec is not very specific about it, however, such minor difference may still have effect on portability of Clojure codebase into Babashka.

**repro:**

```
(with-out-str ^{(print 2) (print 3)} {:b (print 1)})
```

**expected behavior:**

In Clojure 1.10.3, it returns ```"123"```.

In Babashka, result is `"231"`. 123 would be preferred/expected.

**solution:**

I think it can be addressed for maps by changing evaluation order in https://github.com/babashka/sci/blob/5247b866deeec858480ba2bb22a7d0d3b96c0190/src/sci/impl/evaluator.cljc#L90
 (I have not yet found the location for solving it for sets and vectors.) Can I go ahead with a PR of the change?

**Comment by borkdude** [comment]
Yes, thank you.
