### ISSUE TITLE
Cannot take value of macro

### ISSUE THREAD

**Issue by erdos** [babashka/sci#664]
**version:** bb v0.7.3
**platform:** linux-amd64

**problem:**

Clojure does not allow to take value of macro, Babashka does. I have found the corresponding TODO: https://github.com/babashka/sci/blob/v0.2.8/src/sci/impl/resolve.cljc#L148

I expect it to be a simple change: The `IVar` has an `isMacro` method we can call in resolve-symbol: https://github.com/babashka/sci/blob/20616983a8be69f2c28c4ef453e7a4eb644a12ee/src/sci/impl/vars.cljc#L100

Consideration: what type of exception should be thrown in this case?

**repro:**

Just type `->` in Babashka

**expected behavior**

Should throw exception with message:
```
Can't take value of a macro: #'clojure.core/->
```

**Comment by borkdude** [comment]
Thanks for reporting! Already fixed.
