### ISSUE TITLE
'copy-ns'ed vars don't get :name meta by default

### ISSUE THREAD

**Issue by bobisageek** [babashka/sci#697]
**version**
babashka 0.7.8 (using SCI)

**platform**
Windows binary

**problem**
I was working on something else, and the symptom that led me down this road was that the output of `doc` was missing the function name for certain functions. After investigating, I found that `print-doc` uses the `:name` meta, and that meta isn't added via `sci.core/copy-ns`.

**repro**
```shell
in babashka (note the missing function name):
>bb "(doc clojure.math/to-radians)"
-------------------------
clojure.math/
([deg])
  Converts an angle...
```

**expected behavior**
```shell
in clojure (using deps.clj because Windows):
>deps -e "(require 'clojure.math) (require 'clojure.repl) (clojure.repl/doc clojure.math/to-radians)"
WARNING: Implicit use of clojure.main with options is deprecated, use -M
-------------------------
clojure.math/to-radians
([deg])
  Converts an angle...
```

**Comment by borkdude** [comment]
Btw, you reminded me, I just released a new deps.clj version now.

https://github.com/borkdude/deps.clj/releases/tag/v0.1.1087
