### ISSUE TITLE
(defmethod print-method ...) spans evaluations

### ISSUE THREAD

**Issue by devn** [babashka/sci#726]
**version**

`0.3.5`

**platform**

JVM 17

**problem**

`(defmethod print-method String [obj writer] ...)` spans evaluation.

**repro**

```clojure
(sci/eval-string "(defmethod print-method String [obj w] (.write w (str \"I'm a string: \" obj)))")

(with-open [w (new StringWriter)]
  (sci/binding [sci/out w]
    (let [res (sci/eval-string "(println \"hello\")")]
      (str w))))

;; => "I'm a string: hello\n"
```

**expected behavior**

```clojure
(sci/eval-string "(defmethod print-method String [obj w] (.write w (str \"I'm a string: \" obj)))")

(with-open [w (new StringWriter)]
  (sci/binding [sci/out w]
    (let [res (sci/eval-string "(println \"hello\")")]
      (str w))))

;; => "hello\n"
```

**Sponsor**

it me.

**Comment by borkdude** [comment]
I see several solutions:

- Forbid `print-method` by default
- Allow `print-method` but use a local hierarchy (every context already has a local hierarchy). SCI already has a custom print-method: We already have a custom print-method in SCI:
https://github.com/babashka/sci/blob/afc1c010a71a0640a3c4466b7b3a1cce0ad88eee/src/sci/impl/io.cljc#L14
So if we could get access to the ctx + the ctx hierarchy there, we could solve it properly
- Reset print-method methods after evaluation

One thing to consider is printing of lazy results that escape calls to `eval-string`, etc.

**Comment by devn** [comment]
I agree the easiest is `:sandbox true`, however it feels a bit heavy to have an option which effectively only disallows `print-method`. For this reason, I think I prefer simply preventing `print-method` by default, since IMHO `eval-string` is sort of an implied sandbox unless you explicitly allow other things.

If there were another use case beyond making `print-method` not span evaluations.

Are there? `print-dup` is another, it would seem.

**Comment by borkdude** [comment]
@devn Yep, there are potentially more of those. We could either disallow those by default, which would be breaking, or introduce a new option which strips those from the default vars. I'll think about it some more.

**Comment by borkdude** [comment]
`:host-access true` would also automatically configure JS options which now must be done manually: `{:classes {'js goog/global :allow :all}}`

**Comment by devn** [comment]
That sounds good to me.

**Comment by borkdude** [comment]
I want to revisit this one again. Consider this example:

```
(def local-hierarchy (make-hierarchy))

(defmulti print-method2
  (fn [x writer]
    (let [t (get (meta x) :type)]
      (if (keyword? t) t (class x))))
  :hierarchy #'local-hierarchy)

(deftype XYZ [])

(defmethod print-method2 XYZ [v ^java.io.Writer w]
  (.write w "<<-XYZ->>"))

(defn pr-on2
  {:private true
   :static true}
  [x w]
  (if *print-dup*
    (print-dup x w)
    (print-method2 x w))
  nil)

(pr-on2 (->XYZ) *out*)
(println)
(prn (->XYZ))
```

The `pr-on2` prints using a version of `print-method2` that uses a local hierarchy, which does not affect the host. 

A context already has a local hierarchy, since `derive` etc work in an isolated manner using that.
The only pain is that we should then pass `ctx` as an argument to `println`, `prn`, etc, etc.

**Comment by borkdude** [comment]
Hmm, that complicates things in ways that might not worth pursuing... Either way we can support `:host-access` and later on the above is still possible to make it safer and available with `:host-access false`.

**Comment by borkdude** [comment]
Fixed. `print-method` is now not allowed anymore by default. Calling it will result in an exception that points you to a non-sandboxed solution.
