### ISSUE TITLE
with-meta on a record unexpectedly changes type to SciRecord

### ISSUE THREAD

**Issue by mathesz** [babashka/sci#727]
**version**
0.3.5

**platform**
JDK 17

**problem**
Calling `with-meta` on a record casts the type to `sci.impl.records.SciRecord`.

**repro**

```
(defrecord Person [name])
(def person (map->Person {:name "Smith"}))

(type person)
; user.Person
(prn person)
; #user.Person{:name "Smith"}
; so far so good

(def person-wm (with-meta person {:meta true}))
(type person-wm)
; sci.impl.records.SciRecord

; there is also an issue with printing the record
(prn person-wm)
: java.lang.Class cannot be cast to clojure.lang.Named user 
```

**expected behavior**
Keep original record type.
```
(type person-wm)
; user.Person
```

Workaround: Use `vary-meta`  and `assoc` to append to the metadata map .

**Comment by borkdude** [comment]
What also came up: we should re-enable this check:

https://github.com/babashka/sci/blob/246c6c0639d2b55082e06f03611830b99d6286ef/src/sci/impl/records.cljc#L71

**Comment by borkdude** [comment]
We can go about this in a couple of ways:

- Patch the exposed `with-meta` to a function that preserves the `:sci.impl/...` keys. 
- Use a custom type as the base for SCI records and save the run-time info in separate fields. But this basically means we'd have to re-implement `defrecord`.
