### ISSUE TITLE
Different defrecords with same fields are equal

### ISSUE THREAD

**Issue by frenchy64** [babashka/sci#735]
**version**

```
Via Babashka v0.8.2 REPL
```

**platform**

```
Via Babashka v0.8.2 REPL
Intel Mac
```

**problem**

Different defrecords with same fields are equal. Causes [this](https://github.com/plumatic/schema/blob/1116d1c68347b980ca03a7d4458213b4e13323ae/test/cljc/schema/core_test.cljc#L461) schema unit test to fail, since the schema implementation defines:

```clojure
(clojure.core/defrecord RequiredKey [k])
(clojure.core/defrecord OptionalKey [k])
```

**repro**

```
Babashka v0.8.2 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (defrecord A [a])
#'user/A
user=> (defrecord B [a])
#'user/B
user=> (= (A. 1) (B. 1))
true
```
**expected behavior**

```
Clojure 1.11.1
user=> (defrecord A [a])
user.A
user=> (defrecord B [a])
user.B
user=> (= (A. 1) (B. 1))
false
```

**Comment by borkdude** [comment]
Working on a fix by adding a field `__sci_type` which is different for each record, but this breaks existing libraries that babashka runs in CI:

```
{:test 1785, :pass 10291, :fail 7, :error 2}
```

We probably need to move on to a custom record implementation to make this work properly...
