### ISSUE TITLE
Support clojure.core/*source-path*

### ISSUE THREAD

**Issue by eerohele** [babashka/sci#797]
**Is your feature request related to a problem? Please describe.**

I cannot bind `*source-path*` for use at the REPL.

**Describe the solution you'd like**

I'd like sci to support the `*source-path*` dynamic var.

**Describe alternatives you've considered**

N/A

**Additional context**

In Clojure, you can bind `*source-path*` to show the name of the source file in exception messages and stack traces. For example:

```clojure
user=> (binding [*source-path* "hello.clj"] (-> "(throw (ex-info \"Boom!\" {:a 1}))" read-string eval))
Execution error (ExceptionInfo) at user/eval160 (hello.clj:1).
Boom!

;; cf.

user=> (-> "(throw (ex-info \"Boom!\" {:a 1}))" read-string eval)
Execution error (ExceptionInfo) at user/eval164 (REPL:1). ;; <- "REPL" vs. "hello.clj" above.
Boom!
```

This is useful e.g. for sending code for evaluation from an editor.

FWIW, in Clojure, `*file*` is rather confusingly bound to `"NO_SOURCE_PATH"` by default, and `*source-path*` to `"NO_SOURCE_FILE"`. 🤪 

I'm open to making a PR if you think this feature is worth implementing.

**Comment by borkdude** [comment]
@eerohele Is this related to the `eval-file` metadata perhaps that Clojure also supports?

https://github.com/babashka/sci/commit/a618eb8f5bf10b2c0fc7622cbece38abaeba3099#diff-6440b2234d664da12cda444a32a4ba1aa182d81a606ef27a2a7ccf839ba805c5R1161

I've never understood why we have both `*file*` and `*source-path*`

**Comment by borkdude** [comment]
```
user=> ^{:clojure.core/eval-file "foo.clj"} (/ 1 0)
Execution error (ArithmeticException) at user/eval212 (foo.clj:22).
Divide by zero
```

Notice: `foo.clj`

**Comment by borkdude** [comment]
In bb binding `*file*` has the same effect as `*source-path*` in clojure:

```
user=>  (binding [*file* "hello.clj"] (-> "(throw (ex-info \"Boom!\" {:a 1}))" read-string eval))
clojure.lang.ExceptionInfo: Boom! [at hello.clj:1:1]
```

Is this incorrect?

**Comment by eerohele** [comment]
>Is this related to the eval-file metadata perhaps that Clojure also supports?

[Yes](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/jvm/clojure/lang/Compiler.java#L7148-L7157).

>Is this incorrect?

I don't know, but `*file*` doesn't have the same effect in Clojure:

```clojure
user=> (binding [*file* "hello.clj"] (-> "(throw (ex-info \"Boom!\" {:a 1}))" read-string eval))
Execution error (ExceptionInfo) at user/eval142 (REPL:1).
Boom!
```

It's good to know that I can use `*file` with Babashka. Still, I think adding `*source-path*` would be useful to avoid reader conditionals. Maybe `*source-path*` could just be an alias for `*file*` in Babashka? 🤷🏻‍♂️

**Comment by eerohele** [comment]
>I've never understood why we have both `*file*` and `*source-path*`

Looking at `Compiler.java`, I don't understand it, either. It seems to me it would always be possible to just derive `*source-path*` from `*file*`. Perhaps it's just a wart being retained for backwards compatibility?

**Comment by borkdude** [comment]
I'm not keen at adding another dynamic var since binding it affects performance so I'd say: use the reader conditional.

**Comment by borkdude** [comment]
Ah wait, it's not as bad as say `*ns*`, binding `*file*` doesn't happen in SCI, but only at the "edges" of babashka, so this would probably be OK...

**Comment by borkdude** [comment]
From slack:

Should it just be added as a "dummy" thing, so you don't have to write the reader conditional?

In that case, I think writing the reader conditional might be better than adding it since adding it would maybe create the wrong expectations
