### ISSUE TITLE
Doc/arglists coverage

### ISSUE THREAD

**Issue by mhuebert** [babashka/sci#822]
**version**

0.5.34

**problem**

Docs & arglists missing from things in clojure.core

**repro**

The following will return a map of missing metadata (where `:doc` is present in clojure.core but missing in sci):

```clj 
(defn clojure-meta [name]
   (-> (resolve (symbol "clojure.core" (str name)))
       meta))

(into {}
       (for [[name var] (-> (sci/init {})
                            :env
                            deref
                            :namespaces
                            ('clojure.core))
             :let [sci-meta (meta var)]
             :when (not (:doc sci-meta))
             :let [m (clojure-meta name)]
             :when (:doc m)
             :let [m (select-keys m [:doc :arglists :macro :special-form])
                   m (apply dissoc m (keys sci-meta))]]
         [name m]))
```

Results: https://gist.github.com/mhuebert/72b6ee33e36c84754ae22205e6208bd8

**expected behavior**

I don't know if the goal is 100% coverage, but there are many commonly used macros (eg. `when`) that would benefit from `:doc` and `:arglists`. My use-case is the "eldoc" feature in Maria.cloud where we show usage info for the current operator.

Original discussion: https://clojurians.slack.com/archives/C015LCR9MHD/p1666643541901679

**Comment by borkdude** [comment]
As discussed, PR's welcome for all of those. You can trace back the places where to add them in `namespaces.cljc`.

**Comment by borkdude** [comment]
Updated list:

```
(macroexpand find-ns get-thread-bindings *print-namespace-maps* ns-unmap remove-ns thread-bound? find-var ns-publics isa? swap-vals! *read-eval* *2 eval refer *print-level* alength var-set ns-unalias reset-vals! bound? *print-length* *file* compare-and-set! *err* *default-data-reader-fn* var? ns-aliases read ns-resolve *1 *print-meta* ns-refers extend in-ns create-ns use reset! macroexpand-1 requiring-resolve require *data-readers* *e *clojure-version* instance? the-ns type ns-name *out* ns-map swap! *in* descendants derive load-string ancestors intern ns-interns all-ns ns-imports *3 alias read-string *ns* underive *print-readably* *flush-on-newline* parents deref resolve *print-dup* with-redefs-fn var-get)
```

**Comment by borkdude** [comment]
Added this patch to Clojure which corrects `:dynamic` var metadata for all dynamic vars, since `copy-var` now also picks up on that:

https://clojure.atlassian.net/browse/CLJ-2734

**Comment by borkdude** [comment]
@mhuebert This issue should now completely be resolved. Thanks for the initial work on this!

**Comment by mhuebert** [comment]
@borkdude excellent, thank you!
