### ISSUE TITLE
Support native language shared library compilation and example program on MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [babashka/sci#837]
**Is your feature request related to a problem? Please describe.**
The scripts to compile `libsci` and example c++ and rust programs are written in bash, thus compile libsci under MS-Windows

**Describe the solution you'd like**
Convert libsci compilations scripts to bb tasks.

**Describe alternatives you've considered**
None.

**Additional context**
Trying out `libsci` on MS-Windows. 

I can have a look at converting the scripts to bb tasks if there is no obections. 

I would also like to add a GH action to compile the lib and example language programs across macos, ubuntu and windows, and perhaps invoke each example program as a test that it works.

Thanks

**Comment by borkdude** [comment]
No objections
