### ISSUE TITLE
cljs.core/inc should not resolve to inc in JVM 

### ISSUE THREAD

**Issue by borkdude** [babashka/sci#844]

**Comment by bobisageek** [comment]
just did a quick scan between meetings, and thinking this might be tied to https://github.com/babashka/sci/blob/3d0a6e0ba050c288c5e5985423b77735eef9cf05/src/sci/impl/resolve.cljc#L51-L52

if this isn't helpful, just ignore, but it seems like maybe sci is handling the cljs alias regardless of platform

**Comment by borkdude** [comment]
yes, that's it
