### ISSUE TITLE
new succeeds, dot notation fails for JS class in sci env

### ISSUE THREAD

**Issue by sritchie** [babashka/sci#862]
**version**

0.6.37

**platform**

JVM

**problem**

I found this maybe-bug with SCI via Clerk…

I built custom JS with this namespace:

```
(ns mathbox.clerk-ui
  (:require ["three" :as three]
            [nextjournal.clerk.sci-env]
            [sci.ctx-store]
            [sci.core :as sci]))

(def three-ns
  (-> (into {}
            (map (fn [[k v]] [(symbol k) v]))
            (.entries js/Object three))))

(sci.ctx-store/swap-ctx!
 sci/merge-opts
 {:namespaces  {'three three-ns}})
```

then, in my clerk viewer, I can call constructors with the new keyword:

```
(js/console.log (new three/Color 0xff4136))
```

and I see

![image](https://user-images.githubusercontent.com/69635/209572181-1acbbfd2-32e2-4976-a611-3e6419806648.png)

but if I call `(three/Color. 0xff4136)` instead (ie with dot notation) I get

![image](https://user-images.githubusercontent.com/69635/209572154-0d669a7e-90c8-42d0-9193-70f5b1d7f5f6.png)

**Comment by borkdude** [comment]
Thanks, appreciate the report! It would save me time if you can make isolated repros without project specific config, like this:

``` clojure
(sci/eval-string "(new foo/String nil)" {:namespaces {'foo {'String js/String}}})
#object[String null]

vs:

```
cljs.user=> (sci/eval-string "(foo/String. nil)" {:namespaces {'foo {'String js/String}}})
Execution error (ExceptionInfo) at (<cljs repl>:1).
Could not resolve symbol: String
```

**Comment by sritchie** [comment]
Yes, thank you for the nudge here, I will do this going forward! (Assuming that what you have here is enough repro for this issue, I can do more if not).

**Comment by borkdude** [comment]
Yes, this is sufficient
