### ISSUE TITLE
make `*source-path*` available

### ISSUE THREAD

**Issue by bobisageek** [babashka/sci#922]
**Is your feature request related to a problem? Please describe.**
I started digging into https://github.com/babashka/babashka/issues/1696 a little bit, and the first significant hurdle I hit was that `clojure.core/*source-path*` is not available in bb. Transcriptor binds this for running a repl file.

**Describe the solution you'd like**
I'd like to experiment with adding `*source-path*` to sci (in order to progress towards Transcriptor working from source).

**Describe alternatives you've considered**
Given the small and stable nature of Transcriptor, some alternatives might include:
- forking transcriptor and using `*file*` instead of `*source-path*`
- bundling transcriptor into babashka

**Additional context**
There are some other changes in bb to get Transcriptor working from source, including at least:
- adding `clojure.lang.DynamicClassLoader` constructors
- adding `clojure.main/with-read-known`
- adding `clojure.core.server/repl-read`

Small repro/comparison of clj vs bb:
```shell
$ cat source-path.clj
(println "source-path:" *source-path*)
(println "file:" *file*)

$ clj source-path.clj 
source-path: source-path.clj
file: /home/bob/scratch/source-path.clj

$ bb source-path.clj 
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Could not resolve symbol: *source-path*
...
```

**Comment by borkdude** [comment]
What is the difference between `*file*` and `*source-paths*` in Clojure?

**Comment by bobisageek** [comment]
Just for posterity/note-taking, the only significance I can find is that spec reporting/error reporting stack trace-y things appear to use `*source-path*`, and this is just a difference between clj and bb.

With a slightly hacked up local copy of transcriptor:
**clj using `*source-path*`**
```clojure repl
; this is transcriptor's run, but also taking the var to bind...
user=> (t/run "abc.repl" #'*source-path*)
; ...

;ugly code to trim down the error info
(try
 (throw (ex-info "hi" {}))
 (catch Exception e (get-in (Throwable->map e) [:via 0 :at])))
; note that the file name/line is reported from the repl file being used
=> [cognitect.transcriptor.t_19$eval490 invokeStatic "abc.repl" 4]

(+ 1 2)
=> 3

(check! #{4})
; the repl file name is reported here as well...
Execution error - invalid arguments to cognitect.transcriptor.t-19/eval494 at (abc.repl:9).
```

**clj using `*file*`**
```clojure repl
user=> (t/run "abc.repl" #'*file*)
;...

(try
 (throw (ex-info "hi" {}))
 (catch Exception e (get-in (Throwable->map e) [:via 0 :at])))
; source not reported as nicely...
=> [cognitect.transcriptor.t_21$eval522 invokeStatic "NO_SOURCE_FILE" 4]

(+ 1 2)
=> 3

(check! #{4})
; and here...
Execution error - invalid arguments to cognitect.transcriptor.t-21/eval526 at (REPL:9).
3 - failed: #{4}
```

From my experimenting so far, in bb it looks like these will be reported as '<repl>' (or whatever file calls `t/run`.

This is probably not the biggest deal.  I'll try adding it in bb as suggested, and then there are some other new functions to copy/re-create with sci vars to make progress on Transcriptor.

**Comment by bobisageek** [comment]
`*source-path*` is now bound to the same var as `*file*` in bb; closing this until/unless it's eventually needed/desired to be implemented in SCI
