### ISSUE TITLE
behavioral missmatch: Duplicate keys on literals

### ISSUE THREAD

**Issue by souenzzo** [babashka/sci#923]
**version**

```shell
clj -Sdeps '{:deps{org.babashka/sci {:mvn/version "0.8.41"}}}'
Clojure 1.11.1
```

**platform**

```clojure
user=> (System/getProperty "java.version")
"22.0.2" ;; openjdk on macos M2 probably updated. Also happens on linux :)
```

**problem**

Behavior mismatch: In clojure, a literal with two vars of the same value throws a runtime exception. ~I found this out this week, in the worst way possible.~

**repro**

```clojure
user=> (require '[sci.core :as sci])
nil
user=> (let [a 1 b 2] #{a b})
#{1 2}
user=> (let [a 1 b 1] #{a b})
Execution error (IllegalArgumentException) at user/eval5879 (REPL:1).
Duplicate key: 1
user=> (sci/eval-string "(let [a 1 b 1] #{a b})")  ;; error here.
#{1}
;; expected: exception, actual: a value.
user=> (sci/eval-string "(let [a 1 b 2] #{a b})")
#{1 2}
```

**expected behavior**

```clojure
user=> (sci/eval-string "(let [a 1 b 1] #{a b})")  ;; error here.
Execution error (IllegalArgumentException) at user/eval5879 (REPL:1).
Duplicate key: 1
```

**Comment by souenzzo** [comment]
Extra note: `{a 1 b 1}` also throws!

**Comment by borkdude** [comment]
> Extra note 1: {a 1 b 1} also throws!

Throws in which case, JVM Clojure or SCI?

**Comment by borkdude** [comment]
I'm not sure if checking the dynamic case is worth the extra perf overhead to be honest.

**Comment by souenzzo** [comment]
> Throws in which case, JVM Clojure or SCI?

Throws `Duplicate key` error in JVM. In sci, it simply returns a map with 1 key

> Do the values of a and b matter? 

Yes, everything here is given `(= a b)`

> I don't get this extra note.

It is just highlighting that it happens both in sets `#{}` and maps `{}`


Btw, the related jvm clojrue code:

- https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/PersistentHashSet.java#L57-L59
- https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/PersistentArrayMap.java#L74-L76
- https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/PersistentHashMap.java#L68-L70

relevant commits
- https://github.com/clojure/clojure/commit/e6e39d5931fbdf3dfa68cd2d059b8e26ce45c965
- https://github.com/clojure/clojure/commit/c733148ba0fb3ff7bbab133f5375422972e62d08

cited bug in commit message
- https://clojure.atlassian.net/browse/CLJ-87

**Comment by borkdude** [comment]
Alright, I'll wait for CLJS to fix this first, then I can piggy-back on their "createWithCheck" implementation and then align both the clj + cljs behavior since all the tests are pretty much the same in SCI for CLJ + CLJS

**Comment by borkdude** [comment]
Ah it seems there's something in CLJS we can already use today:

```
cljs.user=> (cljs.core.PersistentHashSet.createWithCheck #js [1 1])
Execution error (Error) at (<cljs repl>:1).
Duplicate key: 1
```
